import React from "react";
import Head from "next/head";
import Header from "../components/Header";

import Footer from "../components/Footer";
import Link from "next/link";
import { Stack, Flex, Text, Wrap, WrapItem ,Image} from "@chakra-ui/react";
import { Breadcrumb, BreadcrumbItem } from "@chakra-ui/react";

function GalleryPage() {
  var images = [
    {
      src: "/images/giris-2.jpeg",
      desc: "",
      alt: "2",
    },
    {
      src: "/images/giris-3.jpeg",
      desc: "",
      alt: "3",
    },
  ];

  return (
    <>
      <Head>
        <title>Foto Galeri | Güven Otel</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <Header />
        <Stack>
          <Stack direction={"column"} mt={5} bg={"gray.200"}>
            <Breadcrumb>
              <BreadcrumbItem>
                <>
                  <Link href={"/"} legacyBehavior>
                    <a>Anasayfa</a>
                  </Link>
                </>
              </BreadcrumbItem>

              <BreadcrumbItem isCurrentPage>
                <Text>Foto Galeri</Text>
              </BreadcrumbItem>
            </Breadcrumb>
            <Flex
              justifyContent={"space-between"}
              direction={{ base: "column", lg: "row" }}
              w={"full"}
              h={{ base: "350px", lg: "250px" }}
              mt={30}
            >
              <Wrap>
                {images.map((img, i) =>(
                  <WrapItem key={i}>
                    <Image w={40} src={img.src} alt={img.alt} />
                  </WrapItem>
                ))}
              </Wrap>
            </Flex>
          </Stack>
        </Stack>
        <Footer />
      </>
    </>
  );
}

export default GalleryPage;
