import React from "react";
import Head from "next/head";
import Header from "../components/Header";
function Gallery() {
  return (
    <>
      <Head>
        <title>Galeri | Güven Otel</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <Header />
      </>
    </>
  );
}

export default Gallery;
