import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";

import {
  Stack,
  Flex,
  Heading,
  HStack,
  Icon,
  Image,
  Text,
  Box,
} from "@chakra-ui/react";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
} from "@chakra-ui/react";
import { FaMapMarkerAlt } from "react-icons/fa";
import { BsFillTelephoneFill } from "react-icons/bs";
import Link from "next/link";

function Contact() {
  return (
    <>
      <Head>
        <title>İletişim | Güven Otel</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Stack>
        <Stack direction={"column"} mt={10} bg={"gray.200"}>
          <Box w={"full"} h={400} overflow={"hidden"}>
            <Image src="/images/lobi-2-contact.jpg"  w={'full'}/>
          </Box>

          <Breadcrumb>
            <BreadcrumbItem>
              <>
                <Link href={"/"} legacyBehavior>
                  <a>Anasayfa</a>
                </Link>
              </>
            </BreadcrumbItem>

            <BreadcrumbItem isCurrentPage>
              <Text>İletisim</Text>
            </BreadcrumbItem>
          </Breadcrumb>
          <Flex
            justifyContent={"space-between"}
            direction={{ base: "column", lg: "row" }}
            w={"full"}
            h={{ base: "350px", lg: "250px" }}
            mt={30}
          >
            <Stack w={{ base: "full", lg: "45%" }}>
              <Heading as="h2" size="xl">
                İletişim Bilgileri
              </Heading>
              <Stack
                spacing={6}
                direction={{ base: "column" }}
                justify={{ base: "space-between" }}
                p={15}
              >
                <HStack>
                  <Icon as={FaMapMarkerAlt} />

                  <Link
                    href={
                      "https://www.google.com/maps/place/G%C3%BCneyyurt,+70402+G%C3%BCneyyurt%2FErmenek%2FKaraman/@36.6822526,32.7908054,14z/data=!3m1!4b1!4m5!3m4!1s0x14dbe962653d308f:0x467dd49399d0d14a!8m2!3d36.68222!4d32.808315"
                    }
                    legacyBehavior
                  >
                    <a target="_blank" rel="noopener noreferrer">
                      Güneyyurt Kasabası Belediye Yanı Ermenek - KARAMAN
                    </a>
                  </Link>
                </HStack>
                <HStack>
                  <Icon as={BsFillTelephoneFill} />
                  <Link href={"tel:+905435403160"} legacyBehavior>
                    <a>0543 540 31 60</a>
                  </Link>
                </HStack>
                <HStack>
                  <Icon as={BsFillTelephoneFill} />
                  <Link href={"tel:+905312486322"} legacyBehavior>
                    <a>0531 248 63 22</a>
                  </Link>
                </HStack>
              </Stack>
            </Stack>

            <Stack
              w={{ base: "full", lg: "45%" }}
              as={"iframe"}
              ratio={1}
              allowFullcreen
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25597.420587230703!2d32.79080535991366!3d36.682252635024184!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14dbe962653d308f%3A0x467dd49399d0d14a!2sG%C3%BCneyyurt%2C%2070402%20G%C3%BCneyyurt%2FErmenek%2FKaraman!5e0!3m2!1str!2str!4v1673271577056!5m2!1str!2str"
            />
          </Flex>
        </Stack>
      </Stack>
      <Footer />
    </>
  );
}

export default Contact;
