import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hotel from "../components/Hotel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Güven Otel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hotel/>
      </main>
    </>
  );
}
